// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bomPraCachorro.Models;

namespace bomPraCachorro.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("bomPraCachorro.Models.Animais", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Especies");

                    b.Property<int>("Idade");

                    b.Property<string>("Nome");

                    b.Property<string>("Raca");

                    b.Property<int>("UserId");

                    b.HasKey("AnimalId");

                    b.HasIndex("Especies");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("bomPraCachorro.Models.Especies", b =>
                {
                    b.Property<int>("EspecieId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.HasKey("EspecieId");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("bomPraCachorro.Models.Pontos", b =>
                {
                    b.Property<int>("PontoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CEP");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<int>("Numero");

                    b.Property<string>("Rua");

                    b.Property<int?>("TipoPontos");

                    b.Property<int?>("Usuarios");

                    b.HasKey("PontoId");

                    b.HasIndex("TipoPontos");

                    b.HasIndex("Usuarios");

                    b.ToTable("Pontos");
                });

            modelBuilder.Entity("bomPraCachorro.Models.TipoPontos", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("ImagemTipo");

                    b.HasKey("TipoId");

                    b.ToTable("TipoPontos");
                });

            modelBuilder.Entity("bomPraCachorro.Models.Usuarios", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cel");

                    b.Property<int>("DDD");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.Property<string>("Sobrenome");

                    b.Property<string>("UserLogin");

                    b.HasKey("UserId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("bomPraCachorro.Models.Animais", b =>
                {
                    b.HasOne("bomPraCachorro.Models.Especies", "Especie")
                        .WithMany()
                        .HasForeignKey("Especies");
                });

            modelBuilder.Entity("bomPraCachorro.Models.Pontos", b =>
                {
                    b.HasOne("bomPraCachorro.Models.TipoPontos", "TipoPonto")
                        .WithMany()
                        .HasForeignKey("TipoPontos");

                    b.HasOne("bomPraCachorro.Models.Usuarios", "UserId")
                        .WithMany()
                        .HasForeignKey("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
